name: Continuos Integration with Github

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1
    - name: Log in to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
        
